### ISSUE TITLE
Улучшить визард на MarketScreen

### ISSUE THREAD

**Issue by mistakster** [Cookies1742/media-calc#10]
Когда открыватся экран, то на пользователю доступно сразу два шага: «Насколько дорогой ваш продукт?» и «Насколько нужен ваш продукт?». Ты предположил, что пользователь будет проходить эти шаги последовательно, прокручивая экран. Но это может быть не так. Тогда возникает непонимание.

Мне кажется, что прокручивать нужно до шага, который ещё не заполнен (например, если пользователь пошёл на второй шаг, то вернуть его на первый, а потом пойти на третий). Или показывать всегда только один шаг, чтобы не было вариантов движения по этому визарду.

С точки зрения кода, там сплошная копипаста. Если нужно, то я могу помочь структурировать эти выбиралки.

**Comment by Cookies1742** [comment]
Да, я думаю стоит, чтобы ты мне подсказал. Понимаю, что накопипастил, но столкнулся с проблемами. Без копипасты я бы создал константу и через итерацию запушил в неё 4 карточки с разными параметрами. Вроде
```
let quest = [];
for (let i = 0; i < 4; i++) { 
  quest.push(<Card number ={i} , handler={func(i)}>)
}
```
Но потом опять возникает вопрос как передать такие параметры как текст и иконку. Опять конфигурацию создавать и доставать из массива по ключу i? У меня интуитивно появляется ощущение, что это коряво.

**Comment by mistakster** [comment]
Не, такие переборы надо в функциональном стиле сделать. В React-компонентах никто `for` не использует. Вместо этого вызывают метод `.map()` у массива. В твоём случае это массив с числами `[1, 2, 3, 4]`. Это самый простой вариант для тебя. Если хочется красоты, то используют функции, которые генерируют такие массивы — например, [_.range()](https://lodash.com/docs/4.17.15#range)

Вообще, если видишь копипасту, то нужно выносить её в отдельную компоненту, которую можно вызывать с разными параметрами. Подумай пока сам как это сделать. В понедельник  (16 декабря) можно днём созвониться будет. Спишемся о времени в телеге.
