### ISSUE TITLE
Ревью — страницы нужно разбить на смысловые блоки

### ISSUE THREAD

**Issue by mistakster** [Cookies1742/media-calc#3]
Например, на странице помощи есть форма, которую можно спокойно вынести в отдельную компоненту. Есть и другие блоки.

Важно держать в голове идею, что компоненты должны быть компактными. Файлы на 400-500 строк кода невозможно воспринимать.

**Comment by Cookies1742** [comment]
Наверное стоит это с тобой обсудить, чтобы ты меня на правильные мысли направил (если не сложно), потому что я убью на это много времени, и не факт, что правильно. Смысловые блоки можно выделять по разному и вероятно есть какие-нибудь best practice, о которых я бы с удовольствием узнал.
