### ISSUE TITLE
Ревью — хуки или методы React-компоненты

### ISSUE THREAD

**Issue by mistakster** [Cookies1742/media-calc#4]
Мне кажется, что нужно придерживаться одного стиля в коде. Использование на одной странице хука `useState`, а на другой — метода `this.setState()` запутывает.

Так же я считаю, что компоненты должны быть проще по своей сути. Если логику можно отделить от представления, то это нужно сделать.

**Comment by Cookies1742** [comment]
> Мне кажется, что нужно придерживаться одного стиля в коде. Использование на одной странице хука `useState`, а на другой — метода `this.setState()` запутывает.

Спасибо за фидбек. Все понятно и конструктивно, я слабо за внятностью кода следил. Все замечания учту и исправлю . Только вот эту проблему хотелось бы обсудить. Я везде старался функциональные компоненты использовать с хуками, но нужно было использовать ref в определенном месте и поэтому компонент классовый и  ,соответственно, использовал setState. В таком случае каким будет оптимальное решение?

**Comment by mistakster** [comment]
Есть хук [useRef](https://ru.reactjs.org/docs/hooks-reference.html#useref).

**Comment by Cookies1742** [comment]
Спасибо, ознакомлюсь.
