### ISSUE TITLE
Компонента списка инструкций

### ISSUE THREAD

**Issue by mistakster** [Cookies1742/media-calc#8]
https://github.com/Cookies1742/media-calc/blob/d748bcf71fbdbc252c6d89bc079b22782eb421eb/screens/MarketScreen.js#L100

Олично, что ты вынес кружки в отдельную компоненту. Тут можно было продолжить выделять сами элементы списка в переиспользуюмую компоненту.

**Comment by Cookies1742** [comment]
Я правильно понимаю, что если я выношу элемент, в котором текст отображается в двух местах по разному, то я передаю текст в пропсах? 
```
<NewElement text1='test1' text2='test2' />  
```
Что делать, если текст большой? Читаемость же хуже станет?

**Comment by mistakster** [comment]
Да, в переиспользуемую компоненту данные передаются в пропсах.

Текст — это данные. Они могут быть вообще в отдельном JSON-файле, который импортируется в компоненту.

```
import { text1, text2 } from './text.json';

<NewElement text1={text1} text2={text2} />
```
